/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type BN from "bn.js";
import type { ContractOptions } from "web3-eth-contract";
import type { EventLog } from "web3-core";
import type { EventEmitter } from "events";
import type {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

export interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export interface PermissionsUpgradable extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): PermissionsUpgradable;
  clone(): PermissionsUpgradable;
  methods: {
    getPermImpl(): NonPayableTransactionObject<string>;

    confirmImplChange(_proposedImpl: string): NonPayableTransactionObject<void>;

    getGuardian(): NonPayableTransactionObject<string>;

    getPermInterface(): NonPayableTransactionObject<string>;

    init(
      _permInterface: string,
      _permImpl: string
    ): NonPayableTransactionObject<void>;
  };
  events: {
    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };
}
