/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type BN from "bn.js";
import type { ContractOptions } from "web3-eth-contract";
import type { EventLog } from "web3-core";
import type { EventEmitter } from "events";
import type {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

export interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export interface Mode extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): Mode;
  clone(): Mode;
  methods: {
    checkAuthorization(_operator: string): NonPayableTransactionObject<boolean>;

    dao(): NonPayableTransactionObject<string>;

    init(_management: string): NonPayableTransactionObject<void>;

    initialized(): NonPayableTransactionObject<boolean>;

    management(): NonPayableTransactionObject<string>;

    setDAO(_dao: string): NonPayableTransactionObject<void>;

    setManagement(_management: string): NonPayableTransactionObject<void>;

    switchMode(): NonPayableTransactionObject<void>;

    switchedToDAO(): NonPayableTransactionObject<boolean>;
  };
  events: {
    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };
}
