name: Continous integration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-javascript:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: javascript

    strategy:
      matrix:
        node-version: [14, 16, 18]

    steps:
      - uses: actions/checkout@v3
      - name:
          Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
          cache-dependency-path: javascript/yarn.lock
      - name: Install dependencies
        run: yarn
      - name: Test
        run: yarn test

  build-java:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: java

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "adopt"
      - name: Build
        run: mvn --batch-mode -DskipTests package

      - name: Test
        run:
          mvn --batch-mode
          -Dmaven.test.failure.ignore=true test
